import { TimeAgoLocales } from "../interfaces";

const locales: TimeAgoLocales = {
    en: {
        ago: "ago",
        justNow: "just now",
        fromNow: "from now",
        seconds: "seconds",
        oneMinuteAgo: "1 minute ago",
        oneMinuteFromNow: "1 minute from now",
        minutes: "minutes",
        oneHourAgo: "1 hour ago",
        oneHourFromNow: "1 hour from now",
        hours: "hours",
        yesterday: "yesterday",
        tomorrow: "tomorrow",
        days: "days",
        lastWeek: "last week",
        nextWeek: "next week",
        weeks: "weeks",
        lastMonth: "last month",
        nextMonth: "next month",
        months: "months",
        lastYear: "last year",
        nextYear: "next year",
        lastCentury: "last century",
        nextCentury: "next century",
        centuries: "centuries",
    },
    id: {
        ago: "yang lalu",
        justNow: "baru saja",
        fromNow: "dari sekarang",
        seconds: "detik",
        oneMinuteAgo: "1 menit yang lalu",
        oneMinuteFromNow: "1 menit lagi",
        minutes: "menit",
        oneHourAgo: "1 jam yang lalu",
        oneHourFromNow: "1 jam lagi",
        hours: "jam",
        yesterday: "kemarin",
        tomorrow: "besok",
        days: "hari",
        lastWeek: "minggu lalu",
        nextWeek: "minggu depan",
        weeks: "minggu",
        lastMonth: "bulan lalu",
        nextMonth: "bulan depan",
        months: "bulan",
        lastYear: "tahun lalu",
        nextYear: "tahun depan",
        lastCentury: "milenia lalu",
        nextCentury: "milenia depan",
        centuries: "milenia",
    },
};

export { locales };